AllCops:
    Exclude:
        - lib/prometheus/api_client/version.rb

AlignHash:
    EnforcedHashRocketStyle: table

Style/TrailingCommaInArguments:
    EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
    EnforcedStyleForMultiline: comma

Metrics/AbcSize:
    Max: 18

Metrics/MethodLength:
    Max: 23

Metrics/BlockLength:
    Exclude:
        - 'spec/**/*.rb'

Metrics/LineLength:
    Exclude:
        - 'spec/**/*.rb'
